// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"goproject/model/orm/model"
)

func newUserVote(db *gorm.DB, opts ...gen.DOOption) userVote {
	_userVote := userVote{}

	_userVote.userVoteDo.UseDB(db, opts...)
	_userVote.userVoteDo.UseModel(&model.UserVote{})

	tableName := _userVote.userVoteDo.TableName()
	_userVote.ALL = field.NewAsterisk(tableName)
	_userVote.ID = field.NewInt32(tableName, "id")
	_userVote.UserUUID = field.NewString(tableName, "user_uuid")
	_userVote.VoteOption = field.NewInt32(tableName, "vote_option")
	_userVote.VoteTime = field.NewTime(tableName, "vote_time")

	_userVote.fillFieldMap()

	return _userVote
}

type userVote struct {
	userVoteDo

	ALL        field.Asterisk
	ID         field.Int32
	UserUUID   field.String
	VoteOption field.Int32
	VoteTime   field.Time

	fieldMap map[string]field.Expr
}

func (u userVote) Table(newTableName string) *userVote {
	u.userVoteDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userVote) As(alias string) *userVote {
	u.userVoteDo.DO = *(u.userVoteDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userVote) updateTableName(table string) *userVote {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.UserUUID = field.NewString(table, "user_uuid")
	u.VoteOption = field.NewInt32(table, "vote_option")
	u.VoteTime = field.NewTime(table, "vote_time")

	u.fillFieldMap()

	return u
}

func (u *userVote) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userVote) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_uuid"] = u.UserUUID
	u.fieldMap["vote_option"] = u.VoteOption
	u.fieldMap["vote_time"] = u.VoteTime
}

func (u userVote) clone(db *gorm.DB) userVote {
	u.userVoteDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userVote) replaceDB(db *gorm.DB) userVote {
	u.userVoteDo.ReplaceDB(db)
	return u
}

type userVoteDo struct{ gen.DO }

func (u userVoteDo) Debug() *userVoteDo {
	return u.withDO(u.DO.Debug())
}

func (u userVoteDo) WithContext(ctx context.Context) *userVoteDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userVoteDo) ReadDB() *userVoteDo {
	return u.Clauses(dbresolver.Read)
}

func (u userVoteDo) WriteDB() *userVoteDo {
	return u.Clauses(dbresolver.Write)
}

func (u userVoteDo) Session(config *gorm.Session) *userVoteDo {
	return u.withDO(u.DO.Session(config))
}

func (u userVoteDo) Clauses(conds ...clause.Expression) *userVoteDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userVoteDo) Returning(value interface{}, columns ...string) *userVoteDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userVoteDo) Not(conds ...gen.Condition) *userVoteDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userVoteDo) Or(conds ...gen.Condition) *userVoteDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userVoteDo) Select(conds ...field.Expr) *userVoteDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userVoteDo) Where(conds ...gen.Condition) *userVoteDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userVoteDo) Order(conds ...field.Expr) *userVoteDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userVoteDo) Distinct(cols ...field.Expr) *userVoteDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userVoteDo) Omit(cols ...field.Expr) *userVoteDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userVoteDo) Join(table schema.Tabler, on ...field.Expr) *userVoteDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userVoteDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userVoteDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userVoteDo) RightJoin(table schema.Tabler, on ...field.Expr) *userVoteDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userVoteDo) Group(cols ...field.Expr) *userVoteDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userVoteDo) Having(conds ...gen.Condition) *userVoteDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userVoteDo) Limit(limit int) *userVoteDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userVoteDo) Offset(offset int) *userVoteDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userVoteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userVoteDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userVoteDo) Unscoped() *userVoteDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userVoteDo) Create(values ...*model.UserVote) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userVoteDo) CreateInBatches(values []*model.UserVote, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userVoteDo) Save(values ...*model.UserVote) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userVoteDo) First() (*model.UserVote, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVote), nil
	}
}

func (u userVoteDo) Take() (*model.UserVote, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVote), nil
	}
}

func (u userVoteDo) Last() (*model.UserVote, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVote), nil
	}
}

func (u userVoteDo) Find() ([]*model.UserVote, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserVote), err
}

func (u userVoteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserVote, err error) {
	buf := make([]*model.UserVote, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userVoteDo) FindInBatches(result *[]*model.UserVote, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userVoteDo) Attrs(attrs ...field.AssignExpr) *userVoteDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userVoteDo) Assign(attrs ...field.AssignExpr) *userVoteDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userVoteDo) Joins(fields ...field.RelationField) *userVoteDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userVoteDo) Preload(fields ...field.RelationField) *userVoteDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userVoteDo) FirstOrInit() (*model.UserVote, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVote), nil
	}
}

func (u userVoteDo) FirstOrCreate() (*model.UserVote, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVote), nil
	}
}

func (u userVoteDo) FindByPage(offset int, limit int) (result []*model.UserVote, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userVoteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userVoteDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userVoteDo) Delete(models ...*model.UserVote) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userVoteDo) withDO(do gen.Dao) *userVoteDo {
	u.DO = *do.(*gen.DO)
	return u
}
