// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"goproject/model/orm/model"
)

func newVoteStatistic(db *gorm.DB, opts ...gen.DOOption) voteStatistic {
	_voteStatistic := voteStatistic{}

	_voteStatistic.voteStatisticDo.UseDB(db, opts...)
	_voteStatistic.voteStatisticDo.UseModel(&model.VoteStatistic{})

	tableName := _voteStatistic.voteStatisticDo.TableName()
	_voteStatistic.ALL = field.NewAsterisk(tableName)
	_voteStatistic.OptionID = field.NewInt32(tableName, "option_id")
	_voteStatistic.OptionDescription = field.NewString(tableName, "option_description")
	_voteStatistic.VoteCount = field.NewInt32(tableName, "vote_count")

	_voteStatistic.fillFieldMap()

	return _voteStatistic
}

type voteStatistic struct {
	voteStatisticDo

	ALL               field.Asterisk
	OptionID          field.Int32
	OptionDescription field.String
	VoteCount         field.Int32

	fieldMap map[string]field.Expr
}

func (v voteStatistic) Table(newTableName string) *voteStatistic {
	v.voteStatisticDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v voteStatistic) As(alias string) *voteStatistic {
	v.voteStatisticDo.DO = *(v.voteStatisticDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *voteStatistic) updateTableName(table string) *voteStatistic {
	v.ALL = field.NewAsterisk(table)
	v.OptionID = field.NewInt32(table, "option_id")
	v.OptionDescription = field.NewString(table, "option_description")
	v.VoteCount = field.NewInt32(table, "vote_count")

	v.fillFieldMap()

	return v
}

func (v *voteStatistic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *voteStatistic) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 3)
	v.fieldMap["option_id"] = v.OptionID
	v.fieldMap["option_description"] = v.OptionDescription
	v.fieldMap["vote_count"] = v.VoteCount
}

func (v voteStatistic) clone(db *gorm.DB) voteStatistic {
	v.voteStatisticDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v voteStatistic) replaceDB(db *gorm.DB) voteStatistic {
	v.voteStatisticDo.ReplaceDB(db)
	return v
}

type voteStatisticDo struct{ gen.DO }

func (v voteStatisticDo) Debug() *voteStatisticDo {
	return v.withDO(v.DO.Debug())
}

func (v voteStatisticDo) WithContext(ctx context.Context) *voteStatisticDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v voteStatisticDo) ReadDB() *voteStatisticDo {
	return v.Clauses(dbresolver.Read)
}

func (v voteStatisticDo) WriteDB() *voteStatisticDo {
	return v.Clauses(dbresolver.Write)
}

func (v voteStatisticDo) Session(config *gorm.Session) *voteStatisticDo {
	return v.withDO(v.DO.Session(config))
}

func (v voteStatisticDo) Clauses(conds ...clause.Expression) *voteStatisticDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v voteStatisticDo) Returning(value interface{}, columns ...string) *voteStatisticDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v voteStatisticDo) Not(conds ...gen.Condition) *voteStatisticDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v voteStatisticDo) Or(conds ...gen.Condition) *voteStatisticDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v voteStatisticDo) Select(conds ...field.Expr) *voteStatisticDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v voteStatisticDo) Where(conds ...gen.Condition) *voteStatisticDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v voteStatisticDo) Order(conds ...field.Expr) *voteStatisticDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v voteStatisticDo) Distinct(cols ...field.Expr) *voteStatisticDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v voteStatisticDo) Omit(cols ...field.Expr) *voteStatisticDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v voteStatisticDo) Join(table schema.Tabler, on ...field.Expr) *voteStatisticDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v voteStatisticDo) LeftJoin(table schema.Tabler, on ...field.Expr) *voteStatisticDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v voteStatisticDo) RightJoin(table schema.Tabler, on ...field.Expr) *voteStatisticDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v voteStatisticDo) Group(cols ...field.Expr) *voteStatisticDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v voteStatisticDo) Having(conds ...gen.Condition) *voteStatisticDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v voteStatisticDo) Limit(limit int) *voteStatisticDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v voteStatisticDo) Offset(offset int) *voteStatisticDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v voteStatisticDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *voteStatisticDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v voteStatisticDo) Unscoped() *voteStatisticDo {
	return v.withDO(v.DO.Unscoped())
}

func (v voteStatisticDo) Create(values ...*model.VoteStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v voteStatisticDo) CreateInBatches(values []*model.VoteStatistic, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v voteStatisticDo) Save(values ...*model.VoteStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v voteStatisticDo) First() (*model.VoteStatistic, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoteStatistic), nil
	}
}

func (v voteStatisticDo) Take() (*model.VoteStatistic, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoteStatistic), nil
	}
}

func (v voteStatisticDo) Last() (*model.VoteStatistic, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoteStatistic), nil
	}
}

func (v voteStatisticDo) Find() ([]*model.VoteStatistic, error) {
	result, err := v.DO.Find()
	return result.([]*model.VoteStatistic), err
}

func (v voteStatisticDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VoteStatistic, err error) {
	buf := make([]*model.VoteStatistic, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v voteStatisticDo) FindInBatches(result *[]*model.VoteStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v voteStatisticDo) Attrs(attrs ...field.AssignExpr) *voteStatisticDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v voteStatisticDo) Assign(attrs ...field.AssignExpr) *voteStatisticDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v voteStatisticDo) Joins(fields ...field.RelationField) *voteStatisticDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v voteStatisticDo) Preload(fields ...field.RelationField) *voteStatisticDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v voteStatisticDo) FirstOrInit() (*model.VoteStatistic, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoteStatistic), nil
	}
}

func (v voteStatisticDo) FirstOrCreate() (*model.VoteStatistic, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoteStatistic), nil
	}
}

func (v voteStatisticDo) FindByPage(offset int, limit int) (result []*model.VoteStatistic, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v voteStatisticDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v voteStatisticDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v voteStatisticDo) Delete(models ...*model.VoteStatistic) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *voteStatisticDo) withDO(do gen.Dao) *voteStatisticDo {
	v.DO = *do.(*gen.DO)
	return v
}
