// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserVote = "user_votes"

// UserVote mapped from table <user_votes>
type UserVote struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserUUID   string    `gorm:"column:user_uuid;not null" json:"user_uuid"`
	VoteOption int32     `gorm:"column:vote_option;not null" json:"vote_option"`
	VoteTime   time.Time `gorm:"column:vote_time;default:CURRENT_TIMESTAMP" json:"vote_time"`
}

// TableName UserVote's table name
func (*UserVote) TableName() string {
	return TableNameUserVote
}
