// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVoteStatistic = "vote_statistics"

// VoteStatistic mapped from table <vote_statistics>
type VoteStatistic struct {
	OptionID          int32  `gorm:"column:option_id;primaryKey" json:"option_id"`
	OptionDescription string `gorm:"column:option_description" json:"option_description"`
	VoteCount         int32  `gorm:"column:vote_count;not null" json:"vote_count"`
}

// TableName VoteStatistic's table name
func (*VoteStatistic) TableName() string {
	return TableNameVoteStatistic
}
